version: '3.9'
services:
  backend:
    build:
      context: ./
    container_name: docker_backend
    expose:
      - 8000
  nginx:
    build: ./nginx
    container_name: docker_nginx
    depends_on:
      - backend
    ports:
      - 8080:80
