version: '3.9'
services:
  nginx:
    build:
      context: ./nginx/
    container_name: docker_nginx
    depends_on:
      - backend
    ports:
      - "8080:8000"
  backend:
    build:
      context: ./
    container_name: docker_backend
    expose:
      - 8000
    ports:
      - "8000:8000"
